import { useMutation } from '@tanstack/react-query'
import { Sparkles } from 'lucide-react'
import { useState } from 'react'

import { usePermission } from '@/hooks/usePermission'
import { scoreLead } from '@/features/leads/api'
import { Alert } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { PriorityBadge } from '@/components/data-display/PriorityBadge'
import { ApiError } from '@/lib/api-client'
import type { LeadResponse, LeadScoreResponse } from '@/types/api'

/**
 * Mandatory mutation-safety rule (CLAUDE.md §1/§24, Phase 18's own design):
 * the AI's suggested score/priority is held ONLY in this component's local
 * state — never written into the TanStack Query cache, never PATCHed back
 * to the lead. `useMutation` has no query key at all; there is nothing to
 * invalidate or persist. Unmounting this component (navigating away from
 * the lead) or clicking "Score with AI" again both discard the previous
 * result outright.
 */
export function LeadScorePanel({ lead }: { lead: LeadResponse }) {
  const hasLeadRead = usePermission('LEAD_READ')
  const hasAiUse = usePermission('AI_USE')
  const canScore = hasLeadRead && hasAiUse
  const [result, setResult] = useState<LeadScoreResponse | null>(null)

  const mutation = useMutation({
    mutationFn: () => scoreLead(lead.id),
    onSuccess: (data) => setResult(data),
    onError: () => setResult(null),
  })

  if (!canScore) return null

  const isAiDisabled = mutation.isError && mutation.error instanceof ApiError && mutation.error.status === 503

  function handleScore() {
    setResult(null)
    mutation.mutate()
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>AI Suggestion</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-muted-foreground">
            Generated by AI, advisory only — this never changes the lead&rsquo;s actual priority
            (currently <PriorityBadge priority={lead.priority} />).
          </p>
          <Button onClick={handleScore} isLoading={mutation.isPending} disabled={mutation.isPending}>
            {mutation.isPending ? 'Scoring...' : 'Score with AI'}
          </Button>
        </div>

        {isAiDisabled && (
          <Alert variant="info">AI features aren&rsquo;t enabled for this workspace.</Alert>
        )}

        {mutation.isError && !isAiDisabled && (
          <Alert variant="destructive">
            <div className="flex items-center justify-between gap-3">
              <span>Unable to generate an AI score right now. Try again.</span>
              <Button variant="outline" size="sm" onClick={handleScore}>
                Retry
              </Button>
            </div>
          </Alert>
        )}

        {result && (
          <div className="space-y-3 rounded-lg border border-dashed border-primary/30 bg-primary/5 p-4">
            <div className="flex items-center gap-1.5 text-xs font-medium text-primary">
              <Sparkles className="h-3.5 w-3.5" aria-hidden="true" />
              AI suggestion — not an authoritative field
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-0.5">
                <p className="text-xs uppercase tracking-wide text-muted-foreground">Score</p>
                <p className="text-2xl font-semibold tabular-nums text-foreground">{result.score} / 100</p>
              </div>
              <div className="space-y-0.5">
                <p className="text-xs uppercase tracking-wide text-muted-foreground">Suggested priority</p>
                <PriorityBadge priority={result.priority} />
              </div>
            </div>
            <div className="space-y-0.5">
              <p className="text-xs uppercase tracking-wide text-muted-foreground">Reasoning</p>
              <p className="text-sm text-foreground">{result.reasoning}</p>
            </div>
            <div className="space-y-0.5">
              <p className="text-xs uppercase tracking-wide text-muted-foreground">Recommended action</p>
              <p className="text-sm text-foreground">{result.recommendedAction}</p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
